### ISSUE TITLE
Installation failed: Command failed (1)

### ISSUE THREAD

**Issue by ashgreat** [erocoar/ggpol#1]
I tried to install it a couple of times and both times it failed installation. I am using R version 3.4 on MacOS

I get the following error:

** R
Error in .install_package_code_files(".", instdir) : 
files in '/private/var/folders/w0/zf6n6gbd2kd0jlvsm9hlb6kw0000gn/T/RtmpEZgP7p/devtoolsfc6e722fff86/erocoar-ggpol-5840b1a/R' missing from 'Collate' field:
  geom_bartext.R
ERROR: unable to collate and parse R files for package ‘ggpol’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ggpol’
Installation failed: Command failed (1)

**Comment by erocoar** [comment]
Thanks for pointing this out! Could you retry installing from GitHub? It should be fixed now.

**Comment by ashgreat** [comment]
Great! Thanks for fixing it, it worked now.
Btw, just for the record, meanwhile I also updated my R to latest version 3.5
