### ISSUE TITLE
remove outliers without filtering out 

### ISSUE THREAD

**Issue by akhst7** [erocoar/ggpol#11]
I'd like to remove outliers from a box jitter plot.  I tried outlier.color =NA, outlier.alpla=0, and outlier.fill=NA but none of these alone or in comb did not work.  Is there a way to remove outliners from the box jitter plot without manipulating the original df in question ? 

Thanks.

**Comment by erocoar** [comment]
Hi, thanks for pointing out this issue. Could you share some data to reproduce the problem? For me, setting `outlier.color = NA` seems to work, but it might also depend on the shape you're using

**Comment by akhst7** [comment]
Hi Frederick, 

I tried with or without Jitter.shjape but I am still getting out line points.  

If I do;

```
> ggplot(tmp, aes(x =Cluster, y = mean.scaled.GlcCer.total)) +
+ geom_boxjitter( jitter.color = NA, outlier.color = "black, errorbar.draw = TRUE, errorbar.length = 0.2, notch = T) 
```
I do see only outlier dots, but If I do the opposite;

```
> ggplot(tmp, aes(x =Cluster, y = mean.scaled.GlcCer.total)) +
+ geom_boxjitter( jitter.color = "black", outlier.color = NA, errorbar.draw = TRUE, errorbar.length = 0.2, notch = T) 
```
I still see the outliers.   

Attached is the data file in question.  

Thanks for helping.
