### ISSUE TITLE
geom_boxjitter fails without explicit attaching the package

### ISSUE THREAD

**Issue by singmann** [erocoar/ggpol#2]
The following `ggplot2` code works as expected even without attaching the package first:

```
set.seed(221)
df <- data.frame(score = rgamma(150, 4, 1),
                 gender = sample(c("M", "F"), 150, replace = TRUE),
                 genotype = factor(sample(1:3, 150, replace = TRUE)))

ggplot2::ggplot(df, ggplot2::aes(x = gender, y = score)) +
  ggplot2::geom_boxplot() ## works
```

However, the same does not work with `geom_boxjitter`:

```
ggplot2::ggplot(df, ggplot2::aes(x = gender, y = score)) +
  ggpol::geom_boxjitter() ##fails
## Error in alpha(data$fill, data$alpha) : could not find function "alpha"
```

We need to attach the package first, before it works:
```
library("ggpol")
ggplot2::ggplot(df, ggplot2::aes(x = gender, y = score)) +
  geom_boxjitter() ##works
```

Then it also works with `::`:

```
ggplot2::ggplot(df, ggplot2::aes(x = gender, y = score)) +
  ggpol::geom_boxjitter()  ## works now
```

**Comment by erocoar** [comment]
Thanks for pointing this out! I have added the missing imports (`alpha`, `resolution` and `PositionJitter`) to the namespace and it should work with the development version.

**Comment by singmann** [comment]
Thanks. for the fix. I can confirm that it works now. 

Can you let me know here when you push the new version to `CRAN`? I am using this in some new development of one of my packages and will update some examples then.

**Comment by erocoar** [comment]
0.0.4 is on Cran now!

**Comment by singmann** [comment]
Thanks!
