### ISSUE TITLE
Could not find function "geom_parliament"

### ISSUE THREAD

**Issue by gabrielacaesar** [erocoar/ggpol#5]
Hey. I have installed the library, following the steps written on the repository, but I still get the error that the function geom_parliament() wasn't found. I have run the same code which is on ReadMe. It also says that the package 'ggpol' wasn't found, although I have installed it. Thank you for the attention.

**Comment by erocoar** [comment]
Hey, sorry for my late response. What version of R and ggplot2 are you running? Can you find `ggpol` in the path you get via `.libPaths()` ?
